### ISSUE TITLE
libQnnTFLiteDelegate.so missing

### ISSUE THREAD

**Issue by pavlosharhan2** [argmaxinc/WhisperKitAndroid#10]
running make build in docker container results in this:

To build: cd /src/AXIE/scripts/../build_android; ninja -j 12
Running build now...
*****************
ninja: error: '../libs/android/libQnnTFLiteDelegate.so', needed by 'libwhisperax.so', missing and no known rule to make it

Where can i get the needed dependencies? Am i missing some step that is not mentioned in the Readme?

**Comment by bpkeene** [comment]
Hello,

We've reproduced this locally and are resolving cc @keith4ever , thank you for bringing this to our attention.

In the interim, if you rewind to f6137cc2285bf91742cf4b756a446fbf8e25e223 (possibly rebuild the docker image, to create a clean environment), you should not encounter this issue.

**Comment by bpkeene** [comment]
Hi @pavlosharhan2 ,

This issue should be resolved with the tagged issue, can you confirm and close as such?  Pending that, we may close by EOW and ask you to re-open if the issue surfaces or still reproduces for you.

Thank you!
