### ISSUE TITLE
Sony X1 - snap 855 - error while Run axie_tflite

### ISSUE THREAD

**Issue by nongthanhhong** [argmaxinc/WhisperKitAndroid#3]
Hi,

When I try to run the test, I get this error and then my phone stops working (I have to force reboot it). After searching for relevant information but finding nothing, I don't know what to do next.

Thanks for your time.

```
 255|SOV40:/ $ axie_tflite /audio/output_audio_mono.wav tiny
Compiled Oct 31 202419:35:52
AXIE TFLite Runner
Argmax, Inc.

lib dir: /data/local/tmp/lib
cache dir: /data/local/tmp/cache
INFO: Initialized TensorFlow Lite runtime.
WARNING: [QNN Delegate] HTP precision is set as kHtpFp16 but the platform doesn't support kHtpFp16. Ignored the setting.
INFO: [QNN Delegate] Caching: cache_filename of /data/local/tmp/cache/qnn_binary_6604284145099505954.bin isn't available, caching in SAVE MODE.
ERROR: Failed to get HTP platform info. Error 1100
ERROR: Restored original execution plan after delegate application failure.
```

**Comment by atiorh** [comment]
Thanks for the report @nongthanhhong! We are currently in alpha release so I salute your enthusiasm for testing our alpha codebase. 🫡  As part of building up to the beta release, we are actively extending our testing device coverage. Could you please share a link to the product page for your device?(I assume you are talking about Sony Xperia 1 but want to make sure)

**Comment by atiorh** [comment]
Our current Snapdragon test coverage includes devices with:
- Snapdragon 888
- Snapdragon 8 Gen 1
- Snapdragon 8 Gen 2
- Snapdragon 8 Gen 3
so 855 will be a good addition

**Comment by atiorh** [comment]
cc: @keith4ever @a2they  for visibility

**Comment by nongthanhhong** [comment]
@atiorh Sorry for the confusion. Yes, it's [Sony Xperia 1 mark 1 ](https://www.gsmarena.com/sony_xperia_1-9543.php). My device is running on Android 11, and although I've checked that the Snapdragon 855 is supported by QAI, maybe it needs some extra steps in my case?

**Comment by keith4ever** [comment]
Hello @nongthanhhong , thanks for your interest. 
Thanks for the link, and it seems your phone has SM8150 architecture which is not currently supported by QCOM's AI SDK. 
We're currently working with key stake holders to possibly support as many AP as possible, so please check back here, or get a more modern AP. These are currently supported via HTP (NPU) or GPU:

SM8650
SM8550
SM8450
SM8350

**Comment by nongthanhhong** [comment]
@keith4ever Thank you for sharing your hard work. I will try again with a newer, supported device.

**Comment by nongthanhhong** [comment]
Hi, @keith4ever, just come back here with S23u - SM8550. on 8m length audio - I got a well correct transcript and:
 Average model latency:
  Audio Input:   108.710 ms
  Melspectro:    76.060 ms
  Encoder:       326.060 ms
  Decoder:       17.680 ms
  Postproc:      1.080 ms
=========================
Total Duration:  48382.320 ms
, but checking the log seems like it failed to delegate on NPU/GPU. How can I check where I'm wrong?

Thank you and have a good day 😊
## LOG:
AXIE TFLite Runner
Argmax, Inc.

lib dir: /data/local/tmp/lib
cache dir: /data/local/tmp/cache
Creating cache directory: /data/local/tmp/cache
INFO: Initialized TensorFlow Lite runtime.
INFO: [QNN Delegate] Caching: cache_filename of /data/local/tmp/cache/qnn_binary_8316569388647923909.bin isn't available, caching in SAVE MODE.
INFO: Wrote serialized data for model mel_spectrogram2.20.0 (88 B) to /data/local/tmp/cache/mel_spectrogram2.20.0_4183742775783677416.bin
INFO: TfLiteQnnDelegate delegate: 21 nodes delegated out of 21 nodes with 1 partitions.

VERBOSE: Replacing 21 out of 21 node(s) with delegate (TfLiteQnnDelegate) node, yielding 1 partitions for the whole graph.
INFO: Wrote serialized data for model mel_spectrogram2.20.0 (20 B) to /data/local/tmp/cache/mel_spectrogram2.20.0_8577268126971921961.bin
INFO: [QNN Delegate] Caching: cache_filename of /data/local/tmp/cache/qnn_binary_12912538988619984752.bin isn't available, caching in SAVE MODE.
INFO: Wrote serialized data for model whisper_encoder_base2.20.0 (1680 B) to /data/local/tmp/cache/whisper_encoder_base2.20.0_4809695520788379349.bin
VERBOSE: Replacing 419 out of 419 node(s) with delegate (TfLiteQnnDelegate) node, yielding 1 partitions for the whole graph.
INFO: Wrote serialized data for model whisper_encoder_base2.20.0 (20 B) to /data/local/tmp/cache/whisper_encoder_base2.20.0_14245224574025941496.bin
INFO: [QNN Delegate] Caching: cache_filename of /data/local/tmp/cache/qnn_binary_792083847501657808.bin isn't available, caching in SAVE MODE.
INFO: Wrote serialized data for model whisper_decoder_base2.20.0 (3936 B) to /data/local/tmp/cache/whisper_decoder_base2.20.0_14718706179135460764.bin
VERBOSE: Replacing 983 out of 983 node(s) with delegate (TfLiteQnnDelegate) node, yielding 1 partitions for the whole graph.
INFO: Wrote serialized data for model whisper_decoder_base2.20.0 (20 B) to /data/local/tmp/cache/whisper_decoder_base2.20.0_15366836946474653222.bin
INFO: [QNN Delegate] Caching: cache_filename of /data/local/tmp/cache/qnn_binary_18177980569190481050.bin isn't available, caching in SAVE MODE.
INFO: Wrote serialized data for model audio_input2.20.0 (24 B) to /data/local/tmp/cache/audio_input2.20.0_8184959232207587746.bin
VERBOSE: Replacing 5 out of 5 node(s) with delegate (TfLiteQnnDelegate) node, yielding 1 partitions for the whole graph.
INFO: Wrote serialized data for model audio_input2.20.0 (20 B) to /data/local/tmp/cache/audio_input2.20.0_13172141440965276315.bin
postproc vocab size: 51864
INFO: Created TensorFlow Lite delegate for GPU.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
VERBOSE: Replacing 27 out of 42 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 12 partitions for the whole graph.
ERROR: Following operations are not supported by GPU delegate:
DELEGATE TfLiteXNNPackDelegate: Operation is not supported.
LOG_SOFTMAX: Operation is not supported.
SCATTER_ND: Operation is not supported.
ZEROS_LIKE: Operation is not supported.
3 operations will run on the GPU, and the remaining 18 operations will run on the CPU.
VERBOSE: Replacing 3 out of 21 node(s) with delegate (TfLiteGpuDelegateV2) node, yielding 3 partitions for the whole graph.
ERROR: TfLiteGpuDelegate Init: Tensor "model/tf.math.reduce_logsumexp/ReduceLogSumExp/Log" has bad input dims size: 0.
INFO: Created 0 GPU delegate kernels.
ERROR: TfLiteGpuDelegate Prepare: delegate is not initialized
ERROR: Node number 48 (TfLiteGpuDelegateV2) failed to prepare.
ERROR: Restored original execution plan after delegate application failure.
Falling back to default TFLite GPU backend..tflite_init done..

**Comment by keith4ever** [comment]
@nongthanhhong,

I'm glad you got it working. 
The 3 errors are from this line of code, I believe:
https://github.com/argmaxinc/WhisperKitAndroid/blob/main/src/tflite_runner.cpp#L84
which is not a concern, as it may have delegated to another computing resource (NPU or CPU) and therefore you got the right result. 

If you want to try again with NPU (HTP for QCOM), replace the line with this: 

`    TFLITE_INIT_CHECK(postproc->initialize(postproc_model, lib_dir, cache_dir, kHtpBackend));`

**Comment by nongthanhhong** [comment]
@keith4ever, thanks for your time. Can I utilize and integrate this repo as part of the Android app but not just run it as an execution? Are there any sharable documents from our team about using the built *.so* library, cpp native code, etc in an Android app through JNI? 
Even not, I still really appreciate your and your team's efforts. Looking forward to hearing from you soon 😄

**Comment by keith4ever** [comment]
Hi @nongthanhhong , 
You're welcome to develop as it suits your needs.. absolutely you can develop JNI layer around this. 
As we speak, we are also developing JNI layer + sample Android app but we're not yet 100% certain if we can include it in v0.1 Beta release.
